# Generated by Django 4.0.3 on 2022-09-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('Did', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.document')),
            ],
        ),
    ]
