# Generated by Django 4.0.3 on 2022-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_comment_cid_alter_document_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
