# Generated by Django 4.0.3 on 2022-09-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment_author_comment_content_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Did',
            new_name='Doc',
        ),
    ]
